### PR TITLE
fix: nested required fields causes joi validation to assume truthy required array means everything is required

### PR DESCRIPTION
**Pull request by p-mcgowan**
see https://github.com/acr-lfr/generate-it-typescript-server/issues/162 for context

### CODE REVIEW

**Comment by p-mcgowan** [comment]
closes acr-lfr/generate-it-typescript-server#162

**Review by j-d-carmichael — APPROVED** [review]

**Comment by j-d-carmichael** [comment]
do you want to roll out the other prs with this release - think they're all good to go

**Comment by p-mcgowan** [comment]
the open ones? 

not 100% sure where i left off with 115 but even if it doesnt solve the problem it shouldn't break anything™

**Comment by j-d-carmichael** [comment]
yea they all look ok to me the outstanding 3

**Comment by p-mcgowan** [comment]
works for me

**Pull request merged**
