### PR TITLE
jest-update

### PR DESCRIPTION
**Pull request by j-d-carmichael**
https://github.com/acr-lfr/generate-it/issues/119

### CODE REVIEW

**Comment by j-d-carmichael** [comment]
The breaking change in 26 to 27 that affected this project was pretty much just that you can no longer have an async and done on 1 test.

So this:
```
  it('Should build without error', async (done) => {
    try {
      const ymlPath = path.join(process.cwd(), 'test_swagger.yml');
      await openapiNodegen({
        dontRunComparisonTool: false,
        dontUpdateTplCache: false,
        updateDependenciesFromTpl: false,
        mockServer: true,
        swaggerFilePath: ymlPath,
        targetDir: testServerPath,
        template: tplUrl,
      });
      done();
    } catch (e) {
      done(e);
    }
  });
```
had to become this:
```
  it('Should build without error', (done) => {
    const ymlPath = path.join(process.cwd(), 'test_swagger.yml');
    openapiNodegen({
      dontRunComparisonTool: false,
      dontUpdateTplCache: false,
      updateDependenciesFromTpl: false,
      mockServer: true,
      swaggerFilePath: ymlPath,
      targetDir: testServerPath,
      template: tplUrl,
    })
      .then(() => done())
      .catch(e => done(e));
  });
```

**Comment by p-mcgowan** [comment]
looks good - but the old callback style is old school. I would have gone the other way:
```typescript
// the prev tests did this, which didn't really make sense
it('shouldnt explode', async (done) => {
  try {
    const exploded = await definitelyWontExplode();
  } catch (e) {
    done(e);
  }
  expect(exploded).toBe(false);
  done();
});

// this is using the old callback-style
it('shouldnt explode', (done) => {
  definitelyWontExplode()
    .then(exploded => {
      expect(exploded).toBe(false);
    })
    .catch(done);
});

// this is the future
it('shouldnt explode', async () => {
  const exploded = await definitelyWontExplode();
  expect(exploded).toBe(false);
});
```

all 3 are effectively the same, but the async one is probably the simplest as, by default, exceptions are considered to be failed tests. 

also means that when we need to do async stuff (or we want to so that we don't end up with deeply nested promise chains) then we can use the same pattern everywhere

**Review by p-mcgowan — APPROVED** [review]

**Comment by p-mcgowan** [comment]
it's definitely the path of least resistance, but i think we should start using the async pattern for tests (expecially since we already have both)

**Comment by p-mcgowan** [comment]
closes #119

**Comment by j-d-carmichael** [comment]
true, but if the openapiNodegen changes from a Promise<void> to something else then you have to change the expected() output.. but i see what you mean

**Comment by j-d-carmichael** [comment]
I'll just merge this into dev for now though, there is also the other PR 120 to be released to npm by the looks of things - i think you were going to give it a bash on a project when you found a minute

**Pull request merged**
