### PR TITLE
Add an opt-in "typegen" parameter to .nodegenrc which allows us to use external type generators.

### PR DESCRIPTION
**Pull request by zewish**
Adds a new `.nodegenrc` opt-in parameter called `typegen` which overrides the default QuickType schema-to-typescript generator. In case this parameter is not specified the previous code inside the generate-it core is triggered and the same old quicktype types are generated.

This will give us the possibility to have multiple internal or external libraries that generate types for generate-it. It is also the first step to decouple from quicktype (which doesn't see much love from its maintainers lately).

**Example .nodegenrc follows:**
```json
{
   // ...
  "typegen": "./schema-to-typescript.js",
}
```

**Example ./schema-to-typescript.js:**
```js
module.exports.default = async (
  name,
  schema,
  config
) => {
  const typeString = doSomeMagicToGetTypesFromSchema(schema);

  return {
    outputString: `export type ${name} = ${typeString};\n`
  };
};
```

**The following extra changes were required for this to work:**
- The generation of parameters schemas objects was improved in a way that conforms with standards compliant schema-to-types generators (has no effect for QuickType as it still generate the previous types even with the slightly modified schema);
- An extra type called "TypegenFunction" is now exported from generate-it which would allow us to have external modules for type generation in the future;
- Unit tests were added where applicable;

### CODE REVIEW

**Review by p-mcgowan — APPROVED** [review]
Looks good to me

**Comment by j-d-carmichael** [comment]
The nodegenrc docs says how to inject a file, but it is not easy to know what the file should contain.

@zewish Could we get an example file in the readme docs?

**Comment by zewish** [comment]
@j-d-carmichael, example is given here in the issue - I can add it to the docs if you this this would be sufficient?

**Comment by j-d-carmichael** [comment]
Yea that looks like it would be enough... else nobody is looking at this issue when it is closed, so that info will be lost :)

**Comment by zewish** [comment]
@j-d-carmichael, @p-mcgowan, docs improved, example added, including a link to the example heading on the config options page - should be way easier to comprehend now.

**Comment by p-mcgowan** [comment]
Thanks @zewish!

**Pull request merged**
